### ISSUE TITLE
Link to SparsePoser is broken

### ISSUE THREAD

**Issue by herdrick** [UPC-ViRVIG/pymotion#1]
README.md links to https://upc-virvig.github.io/SparsePoser/ which is showing a 404 error.  The subdomain upc-virvig.github.io is no longer working, it appears.

**Comment by JLPM22** [comment]
Hi!

Thanks for giving us the heads-up about the link issue :)

The paper is currently going through the acceptance process. As soon as it's accepted, the link will start working!
