### ISSUE TITLE
bvh.get_data()

### ISSUE THREAD

**Issue by AmirAzz** [UPC-ViRVIG/pymotion#2]
Hello, I used this command last week and it worked :   local_rotations, local_positions, parents, offsets = bvh.get_data()

But today, when I try to run the code, this issue appears:

 
 ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-50-444c35d8dd1a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 local_rotations, local_positions, parents, offsets = bvh.get_data()

ValueError: too many values to unpack (expected 4)

**Comment by dasantonym** [comment]
I think I had the same error suddenly pop up just last week after using the 0.0.1 version extensively over the recent months without having any problems. For me, the error went away when I used a different BVH file (which is not a real fix, of course), so I never really looked into it more closely.

Could it be that some regression was introduced with the last update (0.0.2 or 0.0.3)?

**Comment by AmirAzz** [comment]
Hi , I tried with diffrent Bvh files from diffrent datasets , but the error remains yet!

**Comment by dasantonym** [comment]
Ok, that's different from my experience. Guess we'll have to wait if @JLPM22 has any idea on this.

**Comment by AmirAzz** [comment]
I used :    local_rotations, local_positions, parents, offsets,rotations_orders,joint_names = bvh.get_data()              
and worked !!
I guess maybe in new version this new parameters added !

**Comment by JLPM22** [comment]
Hi!

Thank you for the feedback and for using pymotion!

Last week I updated pymotion so that the BVH class can store the end-sites of the leaf joints. 
Now bvh.get_data() should be used as follows:

local_rotations, local_positions, parents, offsets, end_sites, end_sites_parents = bvh.get_data()

Sorry for the inconvenience, for future updates, I will try to keep compatibility with previous versions.
I will also update the examples in the Readme soon.

Let me know if there are any other issues :)

**Comment by AmirAzz** [comment]
Many Thanks for updating me ...

**Comment by dasantonym** [comment]
Thank you for this great library! I used it in my master's thesis project and I will surely continue to use it in future research projects.

**Comment by JLPM22** [comment]
> Thank you for this great library! I used it in my master's thesis project and I will surely continue to use it in future research projects.

I'm so happy to hear that! :) I'm excited to continue improving the library for future research!
