### ISSUE TITLE
BVH remove_joints() does not update rotation order array.

### ISSUE THREAD

**Issue by jacbib-adsk** [UPC-ViRVIG/pymotion#3]
Thank you for this wonderful library.

It looks like the function BVH.remove_joints() does not update the rotation order array, which could cause problems if the joints have different rotation orders.

This is easy to reproduce:

```
>>> from pymotion.io.bvh import BVH
>>> bvh=BVH()
>>> bvh.load('/path/to/file')
>>> bvh.remove_joints([1])
>>> bvh.data['rotations'].shape
(160, 30, 3)
>>> bvh.data['rot_order'].shape
(31, 3)
```

Note there are 30 rotations and 31 joint orders in this example.
I hope it's an easy fix!
Thanks!

**Comment by JLPM22** [comment]
Hi, thank you for the feedback! I have addressed the issue in the new version :)
Let me know if you find any other problems!

**Comment by jacbib-adsk** [comment]
Amazing!  Thank you for the quick turn-around!

**Comment by dongrongliang** [comment]
“remove_joints“ may end in infinite loop
